# Generated by Django 4.2.11 on 2025-04-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='product',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
