# Generated by Django 4.2.11 on 2025-03-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.DeleteModel(
            name='Email',
        ),
    ]
