# Generated by Django 4.2.11 on 2025-04-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_product_history_name_alter_history_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.ImageField(default='images/profiles/profile_default.png', upload_to='images/profiles/'),
        ),
    ]
